### ISSUE TITLE
A better way to stop tail() call

### ISSUE THREAD

**Issue by cvmiller** [fgimian/paramiko-expect#8]
paramiko-expect is a very useful addition to paramiko itself. The documentation could be improved to give more examples of how to use the timeout and other options.

**Comment by cvmiller** [comment]
Thanks! That looks great.

Craig...

-- 
IPv6 is the future!
http://ipv6-net.blogspot.ca/

**Comment by fgimian** [comment]
No worries Craig, I actually made a little error, it will be fixed on the next commit in 5 minutes :smile:

**Comment by Anonymous98** [comment]
This is an excellent library!
It would be great if you could add a timeout option for tail functionality in python2.7 so that it can be stopped after specified time(like 5 hrs or so). Hence, we wont need a ctrl+c interrupt if we plan on using it for automation.

Thanks for paramikoe, it has been very very useful!

**Comment by fgimian** [comment]
@Anonymous98 thanks for the feedback.  I think that the tail function could use revisiting in general as it writes to stdout.  We could potentially use the return of a callback to indicate when the tailing should stop.  This will allow people to automatically stop after a line is received or after a pre-defined set of time via a custom callback.

I've re-opened this and may examine this as an option in the near future 😄

**Comment by fruch** [comment]
close, done in #24 now we have `stop_callback` parameter that can stop the tail() function
